weights: ./runs/exp76/weights/last.pt
cfg: ''
data: ./data/linz_12.yaml
hyp: data/hyp.scratch.yaml
epochs: 400000
batch_size: 4
img_size:
- 1648
- 1648
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
name: ''
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 8
total_batch_size: 4
world_size: 1
global_rank: -1
